from .cyclegan import CycleGANAdversarialLoss, CycleGANConsistencyLoss, CycleGANIdentityLoss
from .animegan import AnimeGANAdversarialLoss, AnimeGANContentLoss, AnimeGANGrayscaleStyleLoss, AnimeGANColorReconstructionLoss
