model: animegan

data:
  photo_root: /data/train_photo
  anime_style_root: /data/Shinkai/style
  anime_smooth_root: /data/Shinkai/smooth
  image_size: 256

train:
  num_epochs: 100
  batch_size: 4
  num_workers: 1
  save_every: 10
  out_dir: output
  seed: 42
  resume: false
  start_epoch: 0
  ckpt_dir: null

optim:
  g_lr: 0.00008
  d_lr: 0.00016

losses:
  lambda_adv: 300.0
  lambda_con: 1.5
  lambda_gra: 3.0
  lambda_col: 10.0
  lambda_edge: 0.1
  lambda_tv: 0.001
  backbone: vgg19