model: animegan

data:
  photo_root: /data/train_photo
  anime_style_root: /data/Shinkai/style
  anime_smooth_root: /data/Shinkai/smooth
  image_size: 256

train:
  num_epochs: 100
  init_epochs: 1
  batch_size: 4
  num_workers: 1
  save_every: 10
  out_dir: output/Shinkai/animegan
  seed: 42
  resume: false
  start_epoch: 0
  ckpt_dir: null

optim:
  g_lr: 0.00008
  d_lr: 0.00016
  init_lr: 0.0001

losses:
  lambda_adv_g: 300.0
  lambda_adv_d: 1.0
  lambda_con: 1.5
  lambda_gra: 3.0
  lambda_col: 10.0
  lambda_smo: 0.1
  lambda_tv: 1.0
  backbone: vgg19