model: cyclegan

data:
  photo_root: /data/train_photo
  anime_style_root: /data/Shinkai/style
  image_size: 256

train:
  num_epochs: 200
  batch_size: 4
  num_workers: 1
  save_every: 10
  out_dir: output
  seed: 42
  resume: false
  start_epoch: 0
  ckpt_dir: null
  decay_epoch: 100

optim:
  g_lr: 0.0002
  d_lr: 0.0002

losses:
  lambda_adv_g: 1.0
  lambda_adv_d: 1.0
  lambda_cyc: 10.0
  lambda_idt: 5.0